### ISSUE TITLE
May I be a contributor of your project?

### ISSUE THREAD

**Issue by LainHE** [czla/Deblurring#1]
I am an IT student who studying Open Source Software.
I have to contribute and communicate with people on the GitHub.
Actually, I am a newbie about coding, but I could to contribute and help your in different ways.
For examples, writing documentation, design and error correction.
I am also doing the project that blurred images restoration with MATLAB.
The reason why I want join is, I want to learn and understand your method.

Sorry for this
I could not find your public email, so I have to put a issue for asking about that at the end.
Here is my public email by the way: TH591@live.mdx.ac.uk

**Comment by czla** [comment]
Hello, thanks for your support! 
This project comes from my course homework, actually i'm not going to maintain it because *image-deblurring* is not my research interest. If you have any questions, please email me by zlchen@tongji.edu.cn
